### ISSUE TITLE
Boolean parameters should be keyword-only

### ISSUE THREAD

**Issue by qexat** [qexat/pyvism#26]
`throw` signature was mentioned about in #20.

**Comment by trag1c** [comment]
@qexat FYI I also got warnings for these in `runtime/errors.py`:
- `Error._get_ruler_size`
- `Error._get_ruler_space`
- `Error._help_line`

<br>

Unrelated but I also got a warning suggesting that you should use `[*self.info_lines, self.error_line]` instead of `self.info_lines + [self.error_line]` in the 2nd method. The rationale is that "[it] is easier to read and faster".

**Comment by qexat** [comment]
> @qexat FYI I also got warnings for these in `runtime/errors.py`:
> 
> - `Error._get_ruler_size`
> 
> - `Error._get_ruler_space`
> 
> - `Error._help_line`
> 

Yes but these functions are private anyway so it doesn't really matter

**Comment by qexat** [comment]
> Unrelated but I also got a warning suggesting that you should use `[*self.info_lines, self.error_line]` instead of `self.info_lines + [self.error_line]` in the 2nd method. The rationale is that "[it] is easier to read and faster".

I understand your point but please open another issue for this topic.

**Comment by trag1c** [comment]
Ah okay, I personally would make all of them use boolean kwargs

**Comment by qexat** [comment]
> Ah okay, I personally would make all of them use boolean kwargs

If you open a PR to fix this I won't refuse, but it is not a priority right now.
